services:
  db:
    image: postgis/postgis:17-3.5
    container_name: VP_db
    environment:
      - POSTGRES_DB=vehiclePark
      - POSTGRES_USER=park
      - POSTGRES_PASSWORD=park_dev
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U park -d vehiclePark" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: VP_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=vehiclePark
      - DB_USER=park
      - DB_PASSWORD=park_dev
      - HBM2DDL=validate
      - JAVA_OPTS=-Duser.timezone=UTC
      - JAVA_TOOL_OPTIONS=-javaagent:/opentelemetry-javaagent.jar
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_LOGS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=none
      - OTEL_SERVICE_NAME=vehiclePark
      - GH_KEY=${GH_KEY}
    volumes:
      - ./opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./monitoring/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000

#  nginx:
#    container_name: VP_nginx
#    image: nginx:1.29.3
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./src/main/resources/certs:/etc/ssl/certs:ro
#    depends_on:
#      - app