services:
  db:
    image: postgis/postgis:17-3.5
    container_name: VP_db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U {DB_USER} -d {DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: VP_app
    image: ghcr.io/${GITHUB_USERNAME}/${REPO_NAME}:${TAG}
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - RSA_PR_KEY_LOC=${RSA_PR_KEY_LOC}
      - RSA_PUB_KEY_LOC=${RSA_PUB_KEY_LOC}
      - HBM2DDL=validate
      - JAVA_OPTS=-Duser.timezone=UTC
      - GH_KEY=${GH_KEY}
    volumes:
      - ./certs:/app/certs
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: VP_nginx
    image: nginx:1.29.3
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs:ro
    depends_on:
      - app